### ISSUE TITLE
Fix haproxy marathon bridge with containerized setup

### ISSUE THREAD

**Issue by jrslv** [ContainerSolutions/terraform-mesos#21]
For some reason I cannot make it working on [v0.1](https://github.com/ContainerSolutions/terraform-mesos/releases/tag/v0.1) neither. 

The file `/etc/haproxy-marathon-bridge/marathons` seems to never be created.

**Comment by thijsschnitger** [comment]
that file was specific to the google-mesosphere setup. I guess the proper thing to do is to recreate it.

**Comment by frankscholten** [comment]
Closing for now
