### ISSUE TITLE
Issue request for help

### ISSUE THREAD

**Issue by zrml** [ContainerSolutions/terraform-mesos#28]
you say in the README:
## "Back in the Developer Console, go to Compute - Compute Engine - Metadata and click the SSH Keys tab. Add your public SSH key there."

I've jsut downloaded the JSON private key from the console for the services.
I cannot find unfer .gconf or .ssh any Google private key :(

Couls you please help me finding it?

thank you

**Comment by thijsschnitger** [comment]
If you don't have an ssh key yet you can create one using `ssh-keygen`. This will put a key and a .pub file in ~/.ssh. Add the contents of the .pub file to the metadata as described above.

**Comment by zrml** [comment]
ah OK I musunderstood the loop.
Thank you
