### ISSUE TITLE
systemd change

### ISSUE THREAD

**Issue by gbjk** [ContainerSolutions/terraform-mesos#31]
Hi,

I was poking around this repo and I saw a recent change to support systemd.
Having just done the same thing, I was caught by the .override files left in there to turn the services off in the future. (mesos-master, zookeeper and mesos-slave respectively).
I think you need to change those for systemctl disable 

Also, I don't think you need to populate the ip file anymore in /etc/mesos*/, FWIW.

HTH - Just a driveby.

G

**Comment by thijsschnitger** [comment]
@gbjk Thanks for noticing!
