### ISSUE TITLE
Error 409 for resource mymesoscluster-global-net during terraform apply

### ISSUE THREAD

**Issue by m-daros** [ContainerSolutions/terraform-mesos#53]
Hi,

I got a 409 error applying terraform plan (I think terraform is trying to create networkmymesoscluster-global-net twice )

I'm trying with 1 master and 3 slaves because I'm using the free trial of GCP. 
Can anyone help me to understand were is the problem?

Thanks a lot
Massimo

Here is the error trace:

Error applying plan:
2 error(s) occurred:
* module.mesos.google_compute_instance.mesos-master: 1 error(s) occurred:
* Script exited with non-zero exit status: 1
* google_compute_network.mesos-global-net: 1 error(s) occurred:
* google_compute_network.mesos-global-net: Error creating network: googleapi: Error 409: The resource 'projects/<MY-GCP-PROJECT>/global/networks/mymesoscluster-global-net' already exists, alreadyExists

**Comment by thijsschnitger** [comment]
I can't reproduce this. My guess is that mymesoscluster-global-net already exists. Try deleting it before you apply the plan.

**Comment by brando14** [comment]
mymesoscluster-global-net  how to delete this ?

**Comment by thijsschnitger** [comment]
Hey @brando14 it's awesome that you're using these scripts, but they're quite dated. I don't really have the time to sort it out at the moment, I would suggest you try to delete the net using the AWS console.
