### ISSUE TITLE
Support deployment of Mesos snapshot builds

### ISSUE THREAD

**Issue by frankscholten** [ContainerSolutions/terraform-mesos#6]
The Mesos source tree has a <a href="https://github.com/apache/mesos/blob/master/Dockerfile">Dockerfile</a> which you can use to create a snapshot build to test new features.

It would be useful if this module allows you to deploy a snapshot build by specifying a Git url to a commit.

**Comment by thijsschnitger** [comment]
I did a dry run with the latest from git, but it takes ages (like 10 to 20 minutes). It might be wise to look into packer to create images with the mesos stuff preinstalled.

**Comment by jrslv** [comment]
Implemented in #17
